CREATE TABLE IF NOT EXISTS user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) DEFAULT NULL,
    password VARCHAR(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS stored_credentials (
    id INT AUTO_INCREMENT PRIMARY KEY,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    encrypted_data VARCHAR(500) NOT NULL,
    user_id INT NOT NULL,
    iv VARCHAR(255) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user(id)
);
